title: "Data2Code Review"
description: "Quality Issues in LLMs for Code: A Systematic Review"
remote_theme: just-the-docs/just-the-docs

# Site settings
url: "https://kaifeng-he.github.io"
baseurl: "/From-Data-to-Code" # Repository name

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Search settings
search_enabled: true
search:
  rel_url: true

# Color scheme
color_scheme: "dark"

# Custom CSS
sass:
  style: compressed

# Heading anchor links
heading_anchors: true

# Footer content
footer_content: "© 2026 SYSUSELab. Systematic Review on LLM Code Quality."
