title: "From Data to Code"
description: "A Systematic Review of Quality Issues in LLMs for Code"
remote_theme: just-the-docs/just-the-docs

# Site settings
url: "https://kaifeng-he.github.io"
baseurl: "" # the subpath of your site, e.g. /blog

# Search settings
search_enabled: true
search:
  rel_url: true

# Color scheme
color_scheme: "dark"

# Custom CSS
sass:
  style: compressed
aux_links:
  "GitHub Repository":
    - "https://github.com/kaifeng-he/From-Data-to-Code"

# Heading anchor links
heading_anchors: true

# Footer content
footer_content: "© 2026 From-Data-to-Code Team. Systematic Review on LLM Code Quality."
